language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_install:
  - composer --prefer-source install
  - composer require phalcon/zephir:dev-master

before_script:
  - git submodule --quiet update --init --recursive
  - (cd vendor/phalcon/zephir; ./unit-tests/ci/before_install.sh; ./install)
  - ./vendor/bin/zephir generate
  - (cd ext;  ./install; phpenv config-add ../tests/ci/ice.ini)
  - ulimit -c unlimited || true

script:
  - php vendor/bin/phpcs --standard=PSR2 --encoding=utf-8 app/
  - phpunit --configuration tests/phpunit.xml

notifications:
  email:
    - info@iceframework.org