language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_install:
  - composer install --prefer-source --no-scripts

before_script:
  - git submodule --quiet update --init --recursive
  - (cd vendor/phalcon/zephir; ./unit-tests/ci/before_install.sh; ./install)
  - (./vendor/bin/zephir fullclean; ./vendor/bin/zephir generate)
  - (cd ext; export CFLAGS="-g3 -O1 -fno-delete-null-pointer-checks -Wall -fvisibility=hidden -DZEPHIR_RELEASE=1"; phpize && ./configure --enable-ice && make -j2 && sudo make install && phpenv config-add ../tests/ci/ice.ini)
  - ulimit -c unlimited || true
  - phpenv config-rm xdebug.ini

script:
  - valgrind --read-var-info=yes --error-exitcode=1 --fullpath-after= --track-origins=yes --leak-check=full ./vendor/bin/phpunit --configuration tests/phpunit.xml --testsuite=all

after_failure:
  - sudo apt-get -qq install gdb
  - gdb -quiet -command=tests/ci/gdb --args $(phpenv which php) vendor/bin/phpunit --debug --colors --configuration tests/phpunit.xml --testsuite=all

notifications:
  email:
    - info@iceframework.org